### ISSUE TITLE
[BUG]: Error parsing go.mod

### ISSUE THREAD

**Issue by nielscil** [leonsteinhaeuser/git-tag-bump#8] opened 2023-04-16 11:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
parsing go.mod:
	module declares its path as: github.com/leonsteinhaeuser/git-tag-identifier
	        but was required as: github.com/leonsteinhaeuser/git-tag-bump
```

### Expected Behavior

Installing the action and bumping the version

### Version

v1.0.0

### Steps To Reproduce

1. Creating workflow
2. Use the action in a step:
``
        uses: leonsteinhaeuser/git-tag-bump@v1.0.0
        with:
          args: "--bump minor"
``
3. Run workflow

**Comment by leonsteinhaeuser** [comment] 2023-04-16 12:49
Good catch. I missed to rename the project in the go.mod file as well. Thank you so much.

**Comment by leonsteinhaeuser** [comment] 2023-04-16 13:13
@nielscil problem should be solved with version v1.0.1.

**Comment by nielscil** [comment] 2023-04-16 13:57
Thanks, that seems to fix that error. Got now another:

`Run echo "TAG_NUMBER=$(git-tag-bump --bump minor)" >> $GITHUB_OUTPUTS
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/6f3c0648-f94c-4fc0-ae95-766a2de4a760.sh
/home/runner/work/_temp/6f3c0648-f94c-4fc0-ae95-766a2de4a760.sh: line 1: $GITHUB_OUTPUTS: ambiguous redirect
Error: Process completed with exit code 1.`

I believe that this line: https://github.com/leonsteinhaeuser/git-tag-bump/blob/97f9476cb2add93c1f8731e1e41a0f0c075f7925/action.yaml#L32

should be (at least this is how I output in my workflow):

`echo "TAG_NUMBER=$(git-tag-bump ${{ inputs.args }})" >> "$GITHUB_OUTPUT"`

**Comment by leonsteinhaeuser** [comment] 2023-04-16 15:28
I have found the root cause of the problem. The real problem is that the actor used to create the tag is not configured in the gitconfig file, which causes the underlying git library to fail.

**Comment by leonsteinhaeuser** [comment] 2023-04-16 16:28
@nielscil I added two new tags to define the "actor" for the tag creation. At the moment this feature is available under the tag rc `v1.0.2-rc.1`. 

- `--actor-name`
- `--actor-email`

**Comment by nielscil** [comment] 2023-04-17 06:40
Tnx for the update, but i'm not using the create tag right now. Just putting the version in a varaible to use.

**Comment by leonsteinhaeuser** [comment] 2023-04-17 06:55
I am very sorry that you had problems. I tested everything locally, with a fully configured git cli. I will definitely add integration tests in the future, so we can test things like this before they are released.Sent from Outlook for Android

**Comment by leonsteinhaeuser** [comment] 2023-07-12 22:19
@nielscil I just took another look at this problem and found a working solution. I released a fix for this problem today and improved the documentation for this flag. I hope this helps.

I am closing this ticket for now. If you have any questions or suggestions, please open this ticket again.

**Closed by leonsteinhaeuser** 2023-07-12 22:19 UTC
Labels: bug
